name: tattoo
description: "A modern reimplementation of TAT â€” the course helper app for Taipei Tech students"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  cookie_jar: ^4.0.9
  dio_cookie_manager: ^3.3.0
  html: ^0.15.6
  dio_redirect_interceptor: ^1.0.1
  collection: ^1.19.1
  intl: ^0.20.2
  flutter_svg: ^2.2.3
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  riverpod: ^3.2.1
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  flutter_secure_storage: ^10.0.0
  package_info_plus: ^9.0.0
  image_picker: ^1.2.1
  skeletonizer: ^2.1.3
  animations: ^2.1.1
  google_fonts: ^8.0.2
  slang: ^4.12.1
  slang_flutter: ^4.12.1
  http_parser: ^4.1.2
  shared_preferences: ^2.5.4
  flutter_image_compress: ^2.4.0
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  firebase_analytics: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  drift_dev: ^2.31.0
  pointycastle: ^4.0.0
  slang_mcp: ^0.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
